# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\takie\Downloads\Projet_Cpp\Projet-Cpp-Sous-Projet-3-Routage Dynamique\Sous_Projet_3_Routage_Dynamique_Cpp"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\takie\Downloads\Projet_Cpp\Projet-Cpp-Sous-Projet-3-Routage Dynamique\Sous_Projet_3_Routage_Dynamique_Cpp\build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	"C:\Program Files\CMake\bin\ctest.exe" $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\takie\Downloads\Projet_Cpp\Projet-Cpp-Sous-Projet-3-Routage Dynamique\Sous_Projet_3_Routage_Dynamique_Cpp\build\CMakeFiles" "C:\Users\takie\Downloads\Projet_Cpp\Projet-Cpp-Sous-Projet-3-Routage Dynamique\Sous_Projet_3_Routage_Dynamique_Cpp\build\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\takie\Downloads\Projet_Cpp\Projet-Cpp-Sous-Projet-3-Routage Dynamique\Sous_Projet_3_Routage_Dynamique_Cpp\build\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RoutageDynamique

# Build rule for target.
RoutageDynamique: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 RoutageDynamique
.PHONY : RoutageDynamique

# fast build rule for target.
RoutageDynamique/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/build
.PHONY : RoutageDynamique/fast

#=============================================================================
# Target rules for targets named test_Event

# Build rule for target.
test_Event: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 test_Event
.PHONY : test_Event

# fast build rule for target.
test_Event/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Event.dir\build.make CMakeFiles/test_Event.dir/build
.PHONY : test_Event/fast

#=============================================================================
# Target rules for targets named test_Graph

# Build rule for target.
test_Graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 test_Graph
.PHONY : test_Graph

# fast build rule for target.
test_Graph/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Graph.dir\build.make CMakeFiles/test_Graph.dir/build
.PHONY : test_Graph/fast

#=============================================================================
# Target rules for targets named test_PathPlanner

# Build rule for target.
test_PathPlanner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 test_PathPlanner
.PHONY : test_PathPlanner

# fast build rule for target.
test_PathPlanner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/build
.PHONY : test_PathPlanner/fast

#=============================================================================
# Target rules for targets named test_Route

# Build rule for target.
test_Route: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 test_Route
.PHONY : test_Route

# fast build rule for target.
test_Route/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Route.dir\build.make CMakeFiles/test_Route.dir/build
.PHONY : test_Route/fast

#=============================================================================
# Target rules for targets named test_Vehicle

# Build rule for target.
test_Vehicle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 test_Vehicle
.PHONY : test_Vehicle

# fast build rule for target.
test_Vehicle/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Vehicle.dir\build.make CMakeFiles/test_Vehicle.dir/build
.PHONY : test_Vehicle/fast

demos/main.obj: demos/main.cpp.obj
.PHONY : demos/main.obj

# target to build an object file
demos/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/demos/main.cpp.obj
.PHONY : demos/main.cpp.obj

demos/main.i: demos/main.cpp.i
.PHONY : demos/main.i

# target to preprocess a source file
demos/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/demos/main.cpp.i
.PHONY : demos/main.cpp.i

demos/main.s: demos/main.cpp.s
.PHONY : demos/main.s

# target to generate assembly for a file
demos/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/demos/main.cpp.s
.PHONY : demos/main.cpp.s

src/Event.obj: src/Event.cpp.obj
.PHONY : src/Event.obj

# target to build an object file
src/Event.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Event.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Event.dir\build.make CMakeFiles/test_Event.dir/src/Event.cpp.obj
.PHONY : src/Event.cpp.obj

src/Event.i: src/Event.cpp.i
.PHONY : src/Event.i

# target to preprocess a source file
src/Event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Event.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Event.dir\build.make CMakeFiles/test_Event.dir/src/Event.cpp.i
.PHONY : src/Event.cpp.i

src/Event.s: src/Event.cpp.s
.PHONY : src/Event.s

# target to generate assembly for a file
src/Event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Event.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Event.dir\build.make CMakeFiles/test_Event.dir/src/Event.cpp.s
.PHONY : src/Event.cpp.s

src/Factory.obj: src/Factory.cpp.obj
.PHONY : src/Factory.obj

# target to build an object file
src/Factory.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Factory.cpp.obj
.PHONY : src/Factory.cpp.obj

src/Factory.i: src/Factory.cpp.i
.PHONY : src/Factory.i

# target to preprocess a source file
src/Factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Factory.cpp.i
.PHONY : src/Factory.cpp.i

src/Factory.s: src/Factory.cpp.s
.PHONY : src/Factory.s

# target to generate assembly for a file
src/Factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Factory.cpp.s
.PHONY : src/Factory.cpp.s

src/Graph.obj: src/Graph.cpp.obj
.PHONY : src/Graph.obj

# target to build an object file
src/Graph.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Graph.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Graph.dir\build.make CMakeFiles/test_Graph.dir/src/Graph.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/src/Graph.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Vehicle.dir\build.make CMakeFiles/test_Vehicle.dir/src/Graph.cpp.obj
.PHONY : src/Graph.cpp.obj

src/Graph.i: src/Graph.cpp.i
.PHONY : src/Graph.i

# target to preprocess a source file
src/Graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Graph.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Graph.dir\build.make CMakeFiles/test_Graph.dir/src/Graph.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/src/Graph.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Vehicle.dir\build.make CMakeFiles/test_Vehicle.dir/src/Graph.cpp.i
.PHONY : src/Graph.cpp.i

src/Graph.s: src/Graph.cpp.s
.PHONY : src/Graph.s

# target to generate assembly for a file
src/Graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Graph.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Graph.dir\build.make CMakeFiles/test_Graph.dir/src/Graph.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/src/Graph.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Vehicle.dir\build.make CMakeFiles/test_Vehicle.dir/src/Graph.cpp.s
.PHONY : src/Graph.cpp.s

src/PathPlanner.obj: src/PathPlanner.cpp.obj
.PHONY : src/PathPlanner.obj

# target to build an object file
src/PathPlanner.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/PathPlanner.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/src/PathPlanner.cpp.obj
.PHONY : src/PathPlanner.cpp.obj

src/PathPlanner.i: src/PathPlanner.cpp.i
.PHONY : src/PathPlanner.i

# target to preprocess a source file
src/PathPlanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/PathPlanner.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/src/PathPlanner.cpp.i
.PHONY : src/PathPlanner.cpp.i

src/PathPlanner.s: src/PathPlanner.cpp.s
.PHONY : src/PathPlanner.s

# target to generate assembly for a file
src/PathPlanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/PathPlanner.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/src/PathPlanner.cpp.s
.PHONY : src/PathPlanner.cpp.s

src/PathfindingStrategy.obj: src/PathfindingStrategy.cpp.obj
.PHONY : src/PathfindingStrategy.obj

# target to build an object file
src/PathfindingStrategy.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/PathfindingStrategy.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/src/PathfindingStrategy.cpp.obj
.PHONY : src/PathfindingStrategy.cpp.obj

src/PathfindingStrategy.i: src/PathfindingStrategy.cpp.i
.PHONY : src/PathfindingStrategy.i

# target to preprocess a source file
src/PathfindingStrategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/PathfindingStrategy.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/src/PathfindingStrategy.cpp.i
.PHONY : src/PathfindingStrategy.cpp.i

src/PathfindingStrategy.s: src/PathfindingStrategy.cpp.s
.PHONY : src/PathfindingStrategy.s

# target to generate assembly for a file
src/PathfindingStrategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/PathfindingStrategy.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/src/PathfindingStrategy.cpp.s
.PHONY : src/PathfindingStrategy.cpp.s

src/Renderer.obj: src/Renderer.cpp.obj
.PHONY : src/Renderer.obj

# target to build an object file
src/Renderer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Renderer.cpp.obj
.PHONY : src/Renderer.cpp.obj

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Route.obj: src/Route.cpp.obj
.PHONY : src/Route.obj

# target to build an object file
src/Route.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Route.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Event.dir\build.make CMakeFiles/test_Event.dir/src/Route.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Graph.dir\build.make CMakeFiles/test_Graph.dir/src/Route.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/src/Route.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Route.dir\build.make CMakeFiles/test_Route.dir/src/Route.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Vehicle.dir\build.make CMakeFiles/test_Vehicle.dir/src/Route.cpp.obj
.PHONY : src/Route.cpp.obj

src/Route.i: src/Route.cpp.i
.PHONY : src/Route.i

# target to preprocess a source file
src/Route.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Route.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Event.dir\build.make CMakeFiles/test_Event.dir/src/Route.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Graph.dir\build.make CMakeFiles/test_Graph.dir/src/Route.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/src/Route.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Route.dir\build.make CMakeFiles/test_Route.dir/src/Route.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Vehicle.dir\build.make CMakeFiles/test_Vehicle.dir/src/Route.cpp.i
.PHONY : src/Route.cpp.i

src/Route.s: src/Route.cpp.s
.PHONY : src/Route.s

# target to generate assembly for a file
src/Route.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Route.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Event.dir\build.make CMakeFiles/test_Event.dir/src/Route.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Graph.dir\build.make CMakeFiles/test_Graph.dir/src/Route.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/src/Route.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Route.dir\build.make CMakeFiles/test_Route.dir/src/Route.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Vehicle.dir\build.make CMakeFiles/test_Vehicle.dir/src/Route.cpp.s
.PHONY : src/Route.cpp.s

src/Simulation.obj: src/Simulation.cpp.obj
.PHONY : src/Simulation.obj

# target to build an object file
src/Simulation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Simulation.cpp.obj
.PHONY : src/Simulation.cpp.obj

src/Simulation.i: src/Simulation.cpp.i
.PHONY : src/Simulation.i

# target to preprocess a source file
src/Simulation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Simulation.cpp.i
.PHONY : src/Simulation.cpp.i

src/Simulation.s: src/Simulation.cpp.s
.PHONY : src/Simulation.s

# target to generate assembly for a file
src/Simulation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Simulation.cpp.s
.PHONY : src/Simulation.cpp.s

src/Vehicle.obj: src/Vehicle.cpp.obj
.PHONY : src/Vehicle.obj

# target to build an object file
src/Vehicle.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Vehicle.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Vehicle.dir\build.make CMakeFiles/test_Vehicle.dir/src/Vehicle.cpp.obj
.PHONY : src/Vehicle.cpp.obj

src/Vehicle.i: src/Vehicle.cpp.i
.PHONY : src/Vehicle.i

# target to preprocess a source file
src/Vehicle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Vehicle.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Vehicle.dir\build.make CMakeFiles/test_Vehicle.dir/src/Vehicle.cpp.i
.PHONY : src/Vehicle.cpp.i

src/Vehicle.s: src/Vehicle.cpp.s
.PHONY : src/Vehicle.s

# target to generate assembly for a file
src/Vehicle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\RoutageDynamique.dir\build.make CMakeFiles/RoutageDynamique.dir/src/Vehicle.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Vehicle.dir\build.make CMakeFiles/test_Vehicle.dir/src/Vehicle.cpp.s
.PHONY : src/Vehicle.cpp.s

tests/test_Event.obj: tests/test_Event.cpp.obj
.PHONY : tests/test_Event.obj

# target to build an object file
tests/test_Event.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Event.dir\build.make CMakeFiles/test_Event.dir/tests/test_Event.cpp.obj
.PHONY : tests/test_Event.cpp.obj

tests/test_Event.i: tests/test_Event.cpp.i
.PHONY : tests/test_Event.i

# target to preprocess a source file
tests/test_Event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Event.dir\build.make CMakeFiles/test_Event.dir/tests/test_Event.cpp.i
.PHONY : tests/test_Event.cpp.i

tests/test_Event.s: tests/test_Event.cpp.s
.PHONY : tests/test_Event.s

# target to generate assembly for a file
tests/test_Event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Event.dir\build.make CMakeFiles/test_Event.dir/tests/test_Event.cpp.s
.PHONY : tests/test_Event.cpp.s

tests/test_Graph.obj: tests/test_Graph.cpp.obj
.PHONY : tests/test_Graph.obj

# target to build an object file
tests/test_Graph.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Graph.dir\build.make CMakeFiles/test_Graph.dir/tests/test_Graph.cpp.obj
.PHONY : tests/test_Graph.cpp.obj

tests/test_Graph.i: tests/test_Graph.cpp.i
.PHONY : tests/test_Graph.i

# target to preprocess a source file
tests/test_Graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Graph.dir\build.make CMakeFiles/test_Graph.dir/tests/test_Graph.cpp.i
.PHONY : tests/test_Graph.cpp.i

tests/test_Graph.s: tests/test_Graph.cpp.s
.PHONY : tests/test_Graph.s

# target to generate assembly for a file
tests/test_Graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Graph.dir\build.make CMakeFiles/test_Graph.dir/tests/test_Graph.cpp.s
.PHONY : tests/test_Graph.cpp.s

tests/test_PathPlanner.obj: tests/test_PathPlanner.cpp.obj
.PHONY : tests/test_PathPlanner.obj

# target to build an object file
tests/test_PathPlanner.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/tests/test_PathPlanner.cpp.obj
.PHONY : tests/test_PathPlanner.cpp.obj

tests/test_PathPlanner.i: tests/test_PathPlanner.cpp.i
.PHONY : tests/test_PathPlanner.i

# target to preprocess a source file
tests/test_PathPlanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/tests/test_PathPlanner.cpp.i
.PHONY : tests/test_PathPlanner.cpp.i

tests/test_PathPlanner.s: tests/test_PathPlanner.cpp.s
.PHONY : tests/test_PathPlanner.s

# target to generate assembly for a file
tests/test_PathPlanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_PathPlanner.dir\build.make CMakeFiles/test_PathPlanner.dir/tests/test_PathPlanner.cpp.s
.PHONY : tests/test_PathPlanner.cpp.s

tests/test_Route.obj: tests/test_Route.cpp.obj
.PHONY : tests/test_Route.obj

# target to build an object file
tests/test_Route.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Route.dir\build.make CMakeFiles/test_Route.dir/tests/test_Route.cpp.obj
.PHONY : tests/test_Route.cpp.obj

tests/test_Route.i: tests/test_Route.cpp.i
.PHONY : tests/test_Route.i

# target to preprocess a source file
tests/test_Route.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Route.dir\build.make CMakeFiles/test_Route.dir/tests/test_Route.cpp.i
.PHONY : tests/test_Route.cpp.i

tests/test_Route.s: tests/test_Route.cpp.s
.PHONY : tests/test_Route.s

# target to generate assembly for a file
tests/test_Route.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Route.dir\build.make CMakeFiles/test_Route.dir/tests/test_Route.cpp.s
.PHONY : tests/test_Route.cpp.s

tests/test_Vehicle.obj: tests/test_Vehicle.cpp.obj
.PHONY : tests/test_Vehicle.obj

# target to build an object file
tests/test_Vehicle.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Vehicle.dir\build.make CMakeFiles/test_Vehicle.dir/tests/test_Vehicle.cpp.obj
.PHONY : tests/test_Vehicle.cpp.obj

tests/test_Vehicle.i: tests/test_Vehicle.cpp.i
.PHONY : tests/test_Vehicle.i

# target to preprocess a source file
tests/test_Vehicle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Vehicle.dir\build.make CMakeFiles/test_Vehicle.dir/tests/test_Vehicle.cpp.i
.PHONY : tests/test_Vehicle.cpp.i

tests/test_Vehicle.s: tests/test_Vehicle.cpp.s
.PHONY : tests/test_Vehicle.s

# target to generate assembly for a file
tests/test_Vehicle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\test_Vehicle.dir\build.make CMakeFiles/test_Vehicle.dir/tests/test_Vehicle.cpp.s
.PHONY : tests/test_Vehicle.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... test
	@echo ... RoutageDynamique
	@echo ... test_Event
	@echo ... test_Graph
	@echo ... test_PathPlanner
	@echo ... test_Route
	@echo ... test_Vehicle
	@echo ... demos/main.obj
	@echo ... demos/main.i
	@echo ... demos/main.s
	@echo ... src/Event.obj
	@echo ... src/Event.i
	@echo ... src/Event.s
	@echo ... src/Factory.obj
	@echo ... src/Factory.i
	@echo ... src/Factory.s
	@echo ... src/Graph.obj
	@echo ... src/Graph.i
	@echo ... src/Graph.s
	@echo ... src/PathPlanner.obj
	@echo ... src/PathPlanner.i
	@echo ... src/PathPlanner.s
	@echo ... src/PathfindingStrategy.obj
	@echo ... src/PathfindingStrategy.i
	@echo ... src/PathfindingStrategy.s
	@echo ... src/Renderer.obj
	@echo ... src/Renderer.i
	@echo ... src/Renderer.s
	@echo ... src/Route.obj
	@echo ... src/Route.i
	@echo ... src/Route.s
	@echo ... src/Simulation.obj
	@echo ... src/Simulation.i
	@echo ... src/Simulation.s
	@echo ... src/Vehicle.obj
	@echo ... src/Vehicle.i
	@echo ... src/Vehicle.s
	@echo ... tests/test_Event.obj
	@echo ... tests/test_Event.i
	@echo ... tests/test_Event.s
	@echo ... tests/test_Graph.obj
	@echo ... tests/test_Graph.i
	@echo ... tests/test_Graph.s
	@echo ... tests/test_PathPlanner.obj
	@echo ... tests/test_PathPlanner.i
	@echo ... tests/test_PathPlanner.s
	@echo ... tests/test_Route.obj
	@echo ... tests/test_Route.i
	@echo ... tests/test_Route.s
	@echo ... tests/test_Vehicle.obj
	@echo ... tests/test_Vehicle.i
	@echo ... tests/test_Vehicle.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

